name: Windows C++ CI Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt with required modules
        run: |
          echo "QT_PATH=D:\a\ostinato\Qt" >> $env:GITHUB_ENV
          python -m pip install aqtinstall
          python -m aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 --outputdir "$env:QT_PATH"
          python -m aqt install-tool windows desktop tools_qtcreator
          # Check and install available modules
          python -m aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 --outputdir "$env:QT_PATH" --modules qtscript

      - name: Install Protobuf
        run: |
          choco install protoc -y
          echo "PROTOBUF_ROOT=C:\tools\protoc" >> $env:GITHUB_ENV

      - name: Set up MSVC 2019
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.29

      - name: Configure build (qmake)
        shell: cmd
        run: |
          qmake ost.pro -spec win32-msvc "CONFIG+=debug" "DEFINES+=QT_DEPRECATED_WARNINGS"

      - name: Build project (nmake)
        run: nmake /NOLOGO
        env:
          PATH: ${{ env.PATH }};C:\Qt\5.15.2\msvc2019_64\bin
          INCLUDE: ${{ env.INCLUDE }};C:\tools\protoc\include
          LIB: ${{ env.LIB }};C:\tools\protoc\lib

      - name: Run tests (optional)
        run: |
          cd client\release
          Ostinato.exe --test
